### ISSUE TITLE
cannot install yarn or npm

### ISSUE THREAD

**Issue by goprojojo** [wassgha/MirrorOS#12] opened 2017-09-20 06:09 UTC
I followed the manual installation but cannot execute yarn install or npm install:

> pi@RPI3B:~ $ cd MirrorOS
pi@RPI3B:/MirrorOS $ yarn install
bash: yarn: command not found
pi@RPI3B:/MirrorOS $ npm install
bash: npm: command not found

I have the latest Raspbian Stretch on Raspberry Pi 3

**Comment by mainframe2017** [comment] 2017-10-11 19:50
hello team

I am facing a issue dusting npm start command. further details are as in attachment.

Thank you
![npm start issue](https://user-images.githubusercontent.com/25217920/31462814-8f9b7a9a-aeeb-11e7-8442-648b2526ddb4.PNG)

**Comment by goprojojo** [comment] 2017-11-24 03:13
Hi mainframe2017, as you may have noticed there is not much activity here. I moved to forum.magicmirror.builders since the community is more heplful.

**Comment by manojjenago** [comment] 2018-01-26 19:43
Hi,
I am getting the above error as mainframe2017 . Please suggest if anyone has successfully installed and invoked. .. Wassim-it will be great if you guide here ....

**Comment by TheArmy2769** [comment] 2018-02-04 14:53
Hi, I have the same problem, can someone help me?

**Comment by wassgha** [comment] 2018-04-18 05:35
Duplicate of #24 , will fix in a PR that's coming soon.

**Closed by wassgha** 2018-04-18 05:35 UTC
